name: Create Tag CI

on:
  push:
    branches:
      - master
      if: startsWith(github.event.head_commit.message, 'Release')


jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: 0.0.5
          message: "Release 0.0.5"