name: Create Tag CI

on: workflow_dispatch

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: 0.0.7
          message: "Release 0.0.7"